[package]
name = "marge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.177"
clap = { version = "4.3.19", features = ["derive"] }
tui = "0.19.0"
github = "0.1.2"
