[package]
name = "marge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.177"
toml = "0.7.6"
tokio = { version = "1.17", default-features = false, features = ["macros", "rt-multi-thread"] }
clap = { version = "4.3.19", features = ["derive"] }
tui = "0.19.0"
octocrab = "0.28.0"
anyhow = "1.0.72"
